'use strict';
/**
 * blockchainService.js — HoneyChain Backend Blockchain Service
 *
 * Responsibilities:
 *  - Connect to blockchain RPC (Hardhat local or Sepolia testnet)
 *  - Load deployed HoneyChainTraceability contract
 *  - Sign and submit transactions using the backend wallet (NEVER exposed to frontend)
 *  - Read blockchain state
 *  - Verify data integrity
 *  - Handle failures gracefully (blockchain down ≠ app crash)
 */

const { ethers } = require('ethers');
const path = require('path');
const fs = require('fs');

// ─── ABI ────────────────────────────────────────────────────────────────────
// Load ABI from compiled artifacts (generated by `npx hardhat compile`)
function loadABI() {
  const artifactPath = path.join(
    __dirname,
    '../../artifacts/contracts/HoneyChainTraceability.sol/HoneyChainTraceability.json'
  );
  if (!fs.existsSync(artifactPath)) {
    throw new Error(
      'Contract artifact not found. Run: npx hardhat compile\n' +
      `Expected at: ${artifactPath}`
    );
  }
  const artifact = JSON.parse(fs.readFileSync(artifactPath, 'utf8'));
  return artifact.abi;
}

// ─── Singleton connection ────────────────────────────────────────────────────
let _provider = null;
let _signer   = null;
let _contract  = null;
let _initialized = false;
let _available   = false;

async function getConnection() {
  if (_initialized) return { provider: _provider, signer: _signer, contract: _contract, available: _available };

  _initialized = true;

  const rpcUrl     = process.env.BLOCKCHAIN_RPC_URL;
  const privateKey = process.env.BLOCKCHAIN_PRIVATE_KEY;
  const contractAddress = process.env.HONEYCHAIN_CONTRACT_ADDRESS;

  if (!rpcUrl || !privateKey || !contractAddress) {
    console.warn(
      '⚠️  Blockchain not configured — set BLOCKCHAIN_RPC_URL, BLOCKCHAIN_PRIVATE_KEY, ' +
      'HONEYCHAIN_CONTRACT_ADDRESS in server/.env'
    );
    _available = false;
    return { available: false };
  }

  try {
    _provider = new ethers.JsonRpcProvider(rpcUrl);
    // Test connection with timeout
    await Promise.race([
      _provider.getNetwork(),
      new Promise((_, reject) =>
        setTimeout(() => reject(new Error('RPC timeout')), 5000)
      ),
    ]);

    _signer   = new ethers.Wallet(privateKey, _provider);
    const abi = loadABI();
    _contract  = new ethers.Contract(contractAddress, abi, _signer);

    const network = await _provider.getNetwork();
    console.log(`✅ Blockchain connected: chainId=${network.chainId}, contract=${contractAddress}`);
    _available = true;
  } catch (err) {
    console.warn('⚠️  Blockchain connection failed:', err.message);
    _available = false;
  }

  return { provider: _provider, signer: _signer, contract: _contract, available: _available };
}

// Reset singleton (useful for retry after initial failure)
function resetConnection() {
  _provider    = null;
  _signer      = null;
  _contract    = null;
  _initialized = false;
  _available   = false;
}

// ─── Health check ────────────────────────────────────────────────────────────

async function isAvailable() {
  try {
    const conn = await getConnection();
    if (!conn.available) return false;
    // Quick ping
    await Promise.race([
      conn.provider.getBlockNumber(),
      new Promise((_, reject) =>
        setTimeout(() => reject(new Error('ping timeout')), 3000)
      ),
    ]);
    return true;
  } catch {
    return false;
  }
}

// ─── Submit batch proof ───────────────────────────────────────────────────────

/**
 * Submit an initial proof for a honey batch to the blockchain.
 *
 * @param {string} batchId   — e.g. "HC-TN-2026-000001"
 * @param {string} bytes32Hash — 0x-prefixed bytes32 hex (from hashData.hexToBytes32)
 * @returns {{ txHash: string, blockNumber: number }} on success
 * @throws on failure
 */
async function submitBatchProof(batchId, bytes32Hash) {
  const conn = await getConnection();
  if (!conn.available) throw new Error('BLOCKCHAIN_UNAVAILABLE');

  try {
    const tx = await conn.contract.createBatchProof(batchId, bytes32Hash);
    console.log(`⛓  submitBatchProof(${batchId}) tx sent: ${tx.hash}`);
    const receipt = await tx.wait(1); // wait for 1 confirmation
    console.log(`✅ submitBatchProof(${batchId}) confirmed in block ${receipt.blockNumber}`);
    return {
      txHash: receipt.hash,
      blockNumber: receipt.blockNumber,
    };
  } catch (err) {
    // Detect "already exists" — not a fatal error
    if (err.message && err.message.includes('batch proof already exists')) {
      throw new Error('BATCH_PROOF_ALREADY_EXISTS');
    }
    console.error('❌ submitBatchProof error:', err.message);
    throw err;
  }
}

// ─── Submit traceability event ────────────────────────────────────────────────

/**
 * Append a traceability event to an existing batch proof on the blockchain.
 *
 * @param {string} batchId
 * @param {string} eventType — e.g. "LAB_VERIFIED"
 * @param {string} bytes32Hash
 * @returns {{ txHash: string, blockNumber: number }}
 */
async function submitTraceabilityEvent(batchId, eventType, bytes32Hash) {
  const conn = await getConnection();
  if (!conn.available) throw new Error('BLOCKCHAIN_UNAVAILABLE');

  try {
    const tx = await conn.contract.addTraceabilityEvent(batchId, eventType, bytes32Hash);
    console.log(`⛓  addTraceabilityEvent(${batchId}, ${eventType}) tx: ${tx.hash}`);
    const receipt = await tx.wait(1);
    console.log(`✅ addTraceabilityEvent confirmed in block ${receipt.blockNumber}`);
    return { txHash: receipt.hash, blockNumber: receipt.blockNumber };
  } catch (err) {
    console.error('❌ submitTraceabilityEvent error:', err.message);
    throw err;
  }
}

// ─── Read batch proof ─────────────────────────────────────────────────────────

/**
 * Read the stored proof for a batch from the blockchain.
 *
 * @param {string} batchId
 * @returns {{ dataHash: string, createdAt: number, creator: string, exists: boolean } | null}
 */
async function getBatchProof(batchId) {
  const conn = await getConnection();
  if (!conn.available) return null;

  try {
    const [dataHash, createdAt, creator, exists] =
      await conn.contract.getBatchProof(batchId);
    return {
      dataHash,
      createdAt: Number(createdAt),
      creator,
      exists,
    };
  } catch (err) {
    console.error('❌ getBatchProof error:', err.message);
    return null;
  }
}

// ─── Read batch events ────────────────────────────────────────────────────────

/**
 * Read all traceability events for a batch from the blockchain.
 *
 * @param {string} batchId
 * @returns {Array<{ eventType, dataHash, timestamp }>}
 */
async function getBatchEvents(batchId) {
  const conn = await getConnection();
  if (!conn.available) return [];

  try {
    const [eventTypes, dataHashes, timestamps] =
      await conn.contract.getBatchEvents(batchId);
    return eventTypes.map((et, i) => ({
      eventType: et,
      dataHash:  dataHashes[i],
      timestamp: Number(timestamps[i]),
    }));
  } catch (err) {
    console.error('❌ getBatchEvents error:', err.message);
    return [];
  }
}

// ─── Verify batch hash ────────────────────────────────────────────────────────

/**
 * Compare a computed hash against the stored blockchain proof.
 *
 * @param {string} batchId
 * @param {string} bytes32Hash — current computed hash (0x-prefixed bytes32)
 * @returns {'VERIFIED' | 'INTEGRITY_MISMATCH' | 'NO_PROOF' | 'BLOCKCHAIN_UNAVAILABLE'}
 */
async function verifyBatchHash(batchId, bytes32Hash) {
  const conn = await getConnection();
  if (!conn.available) return 'BLOCKCHAIN_UNAVAILABLE';

  try {
    const [matches, proofExists] = await conn.contract.verifyBatchHash(batchId, bytes32Hash);
    if (!proofExists) return 'NO_PROOF';
    return matches ? 'VERIFIED' : 'INTEGRITY_MISMATCH';
  } catch (err) {
    console.error('❌ verifyBatchHash error:', err.message);
    return 'BLOCKCHAIN_UNAVAILABLE';
  }
}

// ─── Get backend wallet address ────────────────────────────────────────────────

async function getBackendWalletAddress() {
  const conn = await getConnection();
  if (!conn.available || !conn.signer) return null;
  return conn.signer.address;
}

module.exports = {
  isAvailable,
  submitBatchProof,
  submitTraceabilityEvent,
  getBatchProof,
  getBatchEvents,
  verifyBatchHash,
  getBackendWalletAddress,
  resetConnection,
};
